language: php
dist: trusty
sudo: false

php:
  - 5.6
  - 7.1

cache:
  directories:
  - $HOME/.composer/cache/files

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
    - LINTS=true COMPOSER_CHANNEL=stable
  exclude:
    - php: 7.1

before_install:
  - /bin/bash -xe travis/before_install.sh

install:
  - /bin/bash -xe travis/install.sh

script:
  - /bin/bash -xe travis/script.sh
